apiVersion: v2
name: ida-otp
description: A Helm chart for MOSIP IDA module
type: application
version: 12.1.2-beta.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - ida-otp
  - ida
maintainers:
  - email: info@mosip.io
    name: MOSIP
