---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kernel-otpmanager-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-otpmanager-service
    spec:
      containers:
      - name: kernel-otpmanager-service
        image: docker-registry.mosip.io:5000/kernel-otpmanager-service
        env:
        - name: active_profile_env
          value: dev
        ports:
        - containerPort: 8085
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-otpmanager-service
spec:
  ports:
    - port: 8085
  selector:
    app: kernel-otpmanager-service

