apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress  
  annotations:    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: "50m"
    ingress.kubernetes.io/proxy-connect-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/send-timeout: "3600"
spec:  
  rules:
  - http:
      paths:
      - path: /v1/uingenerator
        backend:
          serviceName: kernel-uingenerator-service
          servicePort: 8080
      - path: /v1/auditmanager
        backend:
          serviceName: kernel-auditmanager-service
          servicePort: 8081
      - path: /v1/otpnotifier
        backend:
          serviceName: kernel-otpnotification-service
          servicePort: 8082
      - path: /v1/emailnotifier
        backend:
          serviceName: kernel-emailnotification-service
          servicePort: 8083
      - path: /v1/smsnotifier
        backend:
          serviceName: kernel-smsnotification-service
          servicePort: 8084
      - path: /v1/otpmanager
        backend:
          serviceName: kernel-otpmanager-service
          servicePort: 8085
      - path: /v1/masterdata
        backend:
          serviceName: kernel-masterdata-service
          servicePort: 8086
      - path: /v1/cryptomanager
        backend:
          serviceName: kernel-cryptomanager-service
          servicePort: 8087
      - path: /v1/keymanager
        backend:
          serviceName: kernel-keymanager-service
          servicePort: 8088
      - path: /v1/syncdata
        backend:
          serviceName: kernel-syncdata-service
          servicePort: 8089
      - path: /v1/idrepo
        backend:
          serviceName: kernel-idrepo-service
          servicePort: 8090
      - path: /v1/authmanager
        backend:
          serviceName: kernel-auth-service
          servicePort: 8091
      - path: /v1/ldapmanager
        backend:
          serviceName: kernel-ldap-service
          servicePort: 8092
      - path: /v1/licensekeymanager
        backend:
          serviceName: kernel-licensekeymanager-service
          servicePort: 8093
      - path: /v1/applicanttype
        backend:
          serviceName: kernel-applicanttype-service
          servicePort: 8094
      - path: /v1/ridgenerator
        backend:
          serviceName: kernel-ridgenerator-service
          servicePort: 8096
      - path: /v1/tokenidgenerator
        backend:
          serviceName: kernel-tokenidgenerator-service
          servicePort: 8097
      - path: /v1/admin
        backend:
          serviceName: kernel-admin-service
          servicePort: 8099    
      - path: /preregistration/v1/login
        backend:
          serviceName: pre-registration-login-service
          servicePort: 9090
      - path: /preregistration/v1/applications
        backend:
          serviceName: pre-registration-demographic-service
          servicePort: 9092
      - path: /preregistration/v1/documents
        backend:
          serviceName: pre-registration-document-service
          servicePort: 9093
      - path: /preregistration/v1/sync
        backend:
          serviceName: pre-registration-datasync-service
          servicePort: 9094
      - path: /preregistration/v1/appointment
        backend:
          serviceName: pre-registration-booking-service
          servicePort: 9095
      - path: /preregistration/v1/batch
        backend:
          serviceName: pre-registration-batchjob-service
          servicePort: 9096
      - path: /preregistration/v1/transliteration
        backend:
          serviceName: pre-registration-translitration-service
          servicePort: 9098
      - path: /preregistration/v1/notification
        backend:
          serviceName: pre-registration-notification-service
          servicePort: 9099
      - path: /preregistration/v1/qrCode
        backend:
          serviceName: pre-registration-generateqrcode-service
          servicePort: 9091
      - path: /v1/identity
        backend:
          serviceName: authentication-service
          servicePort: 8090
      - path: /pre-registration-ui
        backend:
          serviceName: pre-registration-ui
          servicePort: 80
      - path: /bio-dedupe
        backend:
          serviceName: registration-processor-packet-bio-dedupe-service
          servicePort: 9097
      - path: /abis
        backend:
          serviceName: registration-processor-abis
          servicePort: 9098
      - path: /registration-connector
        backend:
          serviceName: registration-processor-connector-stage
          servicePort: 8091 
      - path: /manual-verification
        backend:
          serviceName: registration-processor-manual-verification-stage
          servicePort: 8084
      - path: /eis
        backend:
          serviceName: registration-processor-external-integration-service
          servicePort: 8201
      - path: /config
        backend:
          serviceName: kernel-config-server
          servicePort: 51000
      - path: /nginx
        backend:
          serviceName: sample-nginx
          servicePort: 80
