---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pre-registration-translitration-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: pre-registration-translitration-service
    spec:
      containers:
      - name: pre-registration-translitration-service
        image: docker-registry.mosip.io:5000/pre-registration-translitration-service
        env:
        - name: active_profile_env
          value: dev
        ports:
        - containerPort: 9098
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: pre-registration-translitration-service
spec:
  ports:
    - port: 9098
  selector:
    app: pre-registration-translitration-service
