---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pre-registration-login-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: pre-registration-login-service
    spec:
      containers:
      - name: pre-registration-login-service
        image: docker-registry.mosip.io:5000/pre-registration-login-service
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.10.0
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        ports:
        - containerPort: 9090
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: pre-registration-login-service
spec:
  ports:
    - port: 9090
  selector:
    app: pre-registration-login-service