---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registration-processor-manual-verification-stage
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: registration-processor-manual-verification-stage
        component: service-hazelcast-server
    spec:
      containers:
      - name: registration-processor-manual-verification-stage
        image: docker-registry.mosip.io:5000/registration-processor-manual-verification-stage
        ports:
          - name: eventbus-port
            containerPort: 5720
        ports:
          - name: hazelcast-port
            containerPort: 5701
        ports:
          - name: verticle-port
            containerPort: 8084
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.10.0
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: registration-processor-manual-verification-stage
spec:
  ports:
    - port: 8084
  selector:
    app: registration-processor-manual-verification-stage

