---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registration-processor-reprocessor-stage
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: registration-processor-reprocessor-stage
        component: service-hazelcast-server
    spec:
      containers:
      - name: registration-processor-reprocessor-stage
        image: docker-registry.mosip.io:5000/registration-processor-reprocessor-stage
        ports:
          - name: eventbus-port
            containerPort: 5750
        ports:
          - name: hazelcast-port
            containerPort: 5701
        env:
        - name: active_profile_env
          value: dev
        - name: spring_config_label_env
          value: 0.10.0
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred

