modules:
  auth:
    enabled: true
    image:
      repository: mosipid/apitest-auth
      tag: 1.3.0
      pullPolicy: Always

  prereg:
    enabled: false

  idrepo:
    enabled: false

  masterdata:
    enabled: false

  partner:
    enabled: false

  pms:
    enabled: false

  esignet:
    enabled: false

  mimoto:
    enabled: false
