## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Add labels to all the deployed resources
##
commonLabels:
  app.kubernetes.io/component: mosip

## Add annotations to all the deployed resources
##
commonAnnotations: {}

## Kubernetes Cluster Domain
##
clusterDomain: cluster.local

## Extra objects to deploy (value evaluated as a template)
##
extraDeploy: []

## Number of nodes
##
replicaCount: 1

service:
  type: ClusterIP
  port: 80
  ## loadBalancerIP for the SuiteCRM Service (optional, cloud specific)
  ## ref: http://kubernetes.io/docs/user-guide/services/#type-loadbalancer
  ##
  ## loadBalancerIP:
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  ##   https: <to set explicitly, choose port between 30000-32767>
  ##
  nodePorts:
    http: ""
    https: ""
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

## Port on which this particular spring service module is running.
springServicePort: 8083

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##

##
# existingConfigmap:

## Command and args for running the container (set to default if not set). Use array form
##
command: ['/bin/bash']
args: ['-c', "/home/${container_user}/scripts/fetch_docker_image_hash_ids.sh"]

## Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1500m
    memory: 3500Mi
  requests:
    cpu: 1000m
    memory: 3500Mi

additionalResources:
  ## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources
  ## Example: java_opts: "-Xms500M -Xmx500M"
  javaOpts: "-Xms2600M -Xmx2600M"

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
## Clamav container already runs as 'mosip' user, so we may not need to enable this
containerSecurityContext:
  enabled: false
  runAsUser: mosip
  runAsNonRoot: true

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: false
  fsGroup: 1001

## Pod affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAffinityPreset: ""

## Pod anti-affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAntiAffinityPreset: soft

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
## Allowed values: soft, hard
##
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  ##
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Pod extra labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Annotations for server pods.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

##  pods' priority.
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
# priorityClassName: ""

## lifecycleHooks for the  container to automate configuration before or after startup.
##
lifecycleHooks: {}

## Custom Liveness probes for
##
customLivenessProbe: {}

## Custom Rediness probes
##
customReadinessProbe: {}

## Update strategy - only really applicable for deployments with RWO PVs attached
## If replicas = 1, an update can get "stuck", as the previous pod remains attached to the
## PV, and the "incoming" pod can never start. Changing the strategy to "Recreate" will
## terminate the single previous pod, so that the new, incoming pod can attach to the PV
##
updateStrategy:
  type: RollingUpdate

## Additional environment variables to set
## Example:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []

## ConfigMap with extra environment variables
##
extraEnvVarsCM:
  - global
  - s3
  - keycloak-host
  - db
  - apitestrig
  - config-server-share
  - artifactory-share
## Secret with extra environment variables
##
extraEnvVarsSecret:
  - apitestrig
  - s3
  - keycloak-client-secrets
  - postgres-postgresql

## Extra volumes to add to the deployment
##
extraVolumes: []

## Extra volume mounts to add to the container
##
extraVolumeMounts: []

## Add init containers to the  pods.
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers:
  - command:
      - /bin/bash
      - -c
      - if [ "$ENABLE_INSECURE" = "true" ]; then HOST=$( env | grep "mosip-api-internal-host"
        |sed "s/mosip-api-internal-host=//g"); if [ -z "$HOST" ]; then echo "HOST
        $HOST is empty; EXITING"; exit 1; fi; openssl s_client -servername "$HOST"
        -connect "$HOST":443  > "$HOST.cer" 2>/dev/null & sleep 2 ; sed -i -ne '/-BEGIN
        CERTIFICATE-/,/-END CERTIFICATE-/p' "$HOST.cer"; cat "$HOST.cer"; /usr/local/openjdk-11/bin/keytool
        -delete -alias "$HOST" -keystore $JAVA_HOME/lib/security/cacerts  -storepass
        changeit; /usr/local/openjdk-11/bin/keytool -trustcacerts -keystore "$JAVA_HOME/lib/security/cacerts"
        -storepass changeit -noprompt -importcert -alias "$HOST" -file "$HOST.cer"
        ; if [ $? -gt 0 ]; then echo "Failed to add SSL certificate for host $host;
        EXITING"; exit 1; fi; cp /usr/local/openjdk-11/lib/security/cacerts /cacerts;
        fi
    env:
      - name: ENABLE_INSECURE
        value: "true"
    envFrom:
      - configMapRef:
          name: global
    image: docker.io/openjdk:11-jre
    imagePullPolicy: Always
    name: cacerts
    resources: {}
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /cacerts
        name: cacerts

## Add sidecars to the  pods.
## Example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}

persistence:
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack).
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  ## ReadWriteMany not supported by AWS gp2
  storageClass:
  accessModes:
    - ReadWriteOnce
  size: 10M
  existingClaim:
  # Dir where config and keys are written inside container
  mountDir:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    pullSecrets: []
    ##   - myRegistryKeySecretName
  ## Init containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    ##
    limits: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##
    requests: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##

## Specifies whether RBAC resources should be created
##
rbac:
  create: true

## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  create: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name:

## Prometheus Metrics
##
metrics:
  enabled: false
  ## Prometheus pod annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations:
    prometheus.io/scrape: "true"

  endpointPath:

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  ##
  serviceMonitor:
    ## If the operator is installed in your cluster, set to true to create a Service Monitor Entry
    ##
    enabled: true
    ## Specify the namespace in which the serviceMonitor resource will be created
    ##
    # namespace: ""
    ## Specify the interval at which metrics should be scraped
    ##
    interval: 10s
    ## Specify the timeout after which the scrape is ended
    ##
    # scrapeTimeout: 30s
    ## Specify Metric Relabellings to add to the scrape endpoint
    ##
    # relabellings:
    ## Specify honorLabels parameter to add the scrape endpoint
    ##
    honorLabels: false
    ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    ##
    additionalLabels: {}

  ## Custom PrometheusRule to be defined
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  ## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
  ##
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ''
    ## List of rules, used as template by Helm.
    ## These are just examples rules inspired from https://awesome-prometheus-alerts.grep.to/rules.html
    # rules:
    #   - alert: RabbitmqDown
    #     expr: rabbitmq_up{service="{{ template "rabbitmq.fullname" . }}"} == 0
    #     for: 5m
    #     labels:
    #       severity: error
    rules: []

## Admin swagger should have only internal access. Hence linked to internal gateway
istio:
  enabled: false
  gateways:
    - istio-system/internal
  prefix:
  corsPolicy:
    allowOrigins:
      - prefix: https://api-internal.sandbox.xyz.net
    allowCredentials: true
    allowHeaders:
      - Accept
      - Accept-Encoding
      - Accept-Language
      - Connection
      - Content-Type
      - Cookie
      - Host
      - Referer
      - Sec-Fetch-Dest
      - Sec-Fetch-Mode
      - Sec-Fetch-Site
      - Sec-Fetch-User
      - Origin
      - Upgrade-Insecure-Requests
      - User-Agent
      - sec-ch-ua
      - sec-ch-ua-mobile
      - sec-ch-ua-platform
      - x-xsrf-token
      - xsrf-token
    allowMethods:
      - GET
      - POST
      - PATCH
      - PUT
      - DELETE

modules:
  prereg:
    enabled: false
    image:
      repository: mosipqa/apitest-prereg
      tag: develop
      pullPolicy: Always
  masterdata:
    enabled: false
    image:
      repository: mosipqa/apitest-masterdata
      tag: develop
      pullPolicy: Always
  idrepo:
    enabled: false
    image:
      repository: mosipqa/apitest-idrepo
      tag: develop
      pullPolicy: Always
  partner:
    enabled: false
    image:
      repository: mosipqa/apitest-pms
      tag: develop
      pullPolicy: Always
  pms:
    enabled: false
    image:
      repository: mosipdev/apitest-pms
      tag: develop
      pullPolicy: Always
  resident:
    enabled: false
    image:
      repository: mosipqa/apitest-resident
      tag: develop
      pullPolicy: Always
  auth:
    enabled: true
    image:
      repository: mosipqa/apitest-auth
      tag: develop
      pullPolicy: Always
  esignet:
    enabled: false
    image:
      repository: mosipqa/apitest-esignet
      tag: develop
      pullPolicy: Always
  mimoto:
    enabled: false
    image:
      repository: mosipqa/apitest-mimoto
      tag: develop
      pullPolicy: Always

crontime: "0 3 * * *"    ## run cronjob every day at 3 AM (time hr: 0-23 )

apitestrig:
  configmaps:
    s3:
      s3-host: 'http://minio.minio:9000'
      s3-user-key: 'admin'
      s3-region: ''
    db:
      db-port: '5432'
      db-su-user: 'postgres'
      db-server: 'api-internal.sandbox.xyz.net'
    apitestrig:
      ENV_USER: 'api-internal.sandbox'
      ENV_ENDPOINT: 'https://api-internal.sandbox.xyz.net'
      ENV_TESTLEVEL: 'smokeAndRegression'
      authDemoServiceBaseURL: http://authdemo.authdemo
      authDemoServicePort: 80
      eSignetDeployed: yes or no
      push-reports-to-s3: 'yes'
      authCertsPath: '/home/mosip/authcerts'
    scripts:
      fetch_docker_image_hash_ids.sh: |
        #!/bin/bash
        sleep 5
        export DOCKER_HASH_ID=$( kubectl get pod "$HOSTNAME" -n "$NS" -o jsonpath='{.status.containerStatuses[*].imageID}' | sed 's/ /\n/g' | grep -v 'istio' | sed 's/docker\-pullable\:\/\///g' )
        export DOCKER_IMAGE=$( kubectl get pod "$HOSTNAME" -n "$NS" -o jsonpath='{.status.containerStatuses[*].image}' | sed 's/ /\n/g' | grep -v 'istio' | sed 's/docker\-pullable\:\/\///g' )
        if [[ -z $DOCKER_HASH_ID ]]; then
        echo "DOCKER_HASH_ID IS EMPTY;EXITING";
        exit 1;
        fi
        echo "DOCKER_HASH_ID ; $DOCKER_HASH_ID"
        echo "DOCKER_IMAGE : $DOCKER_IMAGE"
        kubectl get pods -A -o=jsonpath='{range .items[*]}{.metadata.namespace}{","}{.metadata.labels.app\.kubernetes\.io\/name}{","}{.status.containerStatuses[?(@.name!="istio-proxy")].image}{","}{.status.containerStatuses[?(@.name!="istio-proxy")].imageID}{","}{.metadata.creationTimestamp}{"\n"}' | sed 's/ /\n/g' | grep -vE 'istio*|longhorn*|cattle*|rancher|kube' | sed 's/docker\-pullable\:\/\///g' | sort -u | sed '/,,,/d' | awk -F ',' 'BEGIN {print "{ \"POD_NAME\": \"'$(echo $HOSTNAME)'\", \"DOCKER_IMAGE\": \"'$(echo $DOCKER_IMAGE)'\", \"DOCKER_HASH_ID\": \"'$(echo $DOCKER_HASH_ID)'\", \"k8s-cluster-image-list\": ["} {print "{"} {print "\"namespace\": \"" $1 "\","} {print "\"app_name\": \"" $2 "\","} {print "\"docker_image_name\": \"" $3 "\","} {print "\"docker_image_id\": \"" $4 "\","} {print "\"creation_timestamp\": \"" $5 "\"" } {print "},"} END {print "]}"}' | sed -z 's/},\n]/}\n]/g' | jq -r . | tee -a images-list.json
        ## run entrypoint script
        sleep 5
        cd /home/${container_user}/
        bash ./entrypoint.sh
  secrets:
    apitestrig:
  volumes:
    configmaps:
      scripts:
        defaultMode: 0777
        volumeMounts:
          mountPath: '/home/mosip/scripts/'

enable_insecure: false
