apiVersion: v2
name: ida-internal
description: A Helm chart for MOSIP IDA module
type: application
version: 1.3.0-beta.2-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - ida-internal
  - ida
maintainers:
  - email: info@mosip.io
    name: MOSIP
